import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Poppins } from "next/font/google";
import NavbarComponent from "./components/Navbar";
const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <NavbarComponent></NavbarComponent>
        <div className="h-full">
      {children}
      </div>
      <footer className="w-full mt-10 p-4 text-center bottom-0 left-0">
      Made with <span style={{color:"red"}}>&#9829;</span> by Pratyanch Jain
      </footer>
      </body>
    </html>
  );
}
